import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('outocut', {
  engineConnection: () => ipcRenderer.invoke('engine:connection'),
  engineLogs: () => ipcRenderer.invoke('engine:logs'),
  clearEngineLogs: () => ipcRenderer.invoke('engine:clearLogs'),
  selectDirectory: () => ipcRenderer.invoke('dialog:selectDirectory'),
  selectDirectories: () => ipcRenderer.invoke('dialog:selectDirectories'),
  selectFile: (filters?: Electron.FileFilter[]) => ipcRenderer.invoke('dialog:selectFile', filters),
  selectFiles: (filters?: Electron.FileFilter[]) => ipcRenderer.invoke('dialog:selectFiles', filters),
  saveGeneratedImage: (request: { source: string; suggestedName: string; outputDirectory?: string; relativeDirectory?: string }) => ipcRenderer.invoke('image:saveGenerated', request),
  competitorOpen: (url: string) => ipcRenderer.invoke('competitor:open', url),
  competitorStatus: () => ipcRenderer.invoke('competitor:status'),
  competitorCollect: (url?: string) => ipcRenderer.invoke('competitor:collect', url),
  listImageFiles: (directory: string) => ipcRenderer.invoke('folder:listImageFiles', directory),
  listAudioFiles: (directory: string) => ipcRenderer.invoke('folder:listAudioFiles', directory),
  previewBatchRename: (request: { directory: string; templateName: string; rule: string }) => ipcRenderer.invoke('folder:previewBatchRename', request),
  executeBatchRename: (request: { directory: string; templateName: string; rule: string }) => ipcRenderer.invoke('folder:executeBatchRename', request),
  openPath: (path: string) => ipcRenderer.invoke('shell:openPath', path),
  pathToFileUrl: (path: string) => ipcRenderer.invoke('path:toFileUrl', path),
  changeWorkspaceRoot: () => ipcRenderer.invoke('workspace:changeRoot'),
  readFontBytes: (path: string) => ipcRenderer.invoke('font:readBytes', path),
  qianchuanStatus: () => ipcRenderer.invoke('qianchuan:status'),
  qianchuanScanDirectory: (directory: string) => ipcRenderer.invoke('qianchuan:scanDirectory', directory),
  qianchuanConfigure: (config: { batchSize?: number; batchTimeoutSeconds?: number; maxConcurrentEntrances?: number; sharedEntrances?: boolean }) => ipcRenderer.invoke('qianchuan:configure', config),
  qianchuanOpenChrome: () => ipcRenderer.invoke('qianchuan:openChrome'),
  qianchuanDiscoverEntrances: () => ipcRenderer.invoke('qianchuan:discoverEntrances'),
  qianchuanAssignEntranceDirectory: (entranceId: string, directory: string) => ipcRenderer.invoke('qianchuan:assignEntranceDirectory', entranceId, directory),
  qianchuanAssignEntranceDirectories: (entranceId: string, directories: string[]) => ipcRenderer.invoke('qianchuan:assignEntranceDirectories', entranceId, directories),
  qianchuanAssignSharedDirectories: (directories: string[]) => ipcRenderer.invoke('qianchuan:assignSharedDirectories', directories),
  qianchuanRenameEntrance: (entranceId: string, name: string) => ipcRenderer.invoke('qianchuan:renameEntrance', entranceId, name),
  qianchuanFocusEntrance: (entranceId: string) => ipcRenderer.invoke('qianchuan:focusEntrance', entranceId),
  qianchuanStart: () => ipcRenderer.invoke('qianchuan:start'),
  qianchuanStartEntrance: (entranceId: string) => ipcRenderer.invoke('qianchuan:startEntrance', entranceId),
  qianchuanPause: () => ipcRenderer.invoke('qianchuan:pause'),
  qianchuanResume: () => ipcRenderer.invoke('qianchuan:resume'),
  qianchuanStop: () => ipcRenderer.invoke('qianchuan:stop'),
  qianchuanRetryFailed: () => ipcRenderer.invoke('qianchuan:retryFailed'),
  qianchuanConfirmSucceeded: (fileIds: string[]) => ipcRenderer.invoke('qianchuan:confirmSucceeded', fileIds),
  onQianchuanStatus: (listener: (snapshot: unknown) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, snapshot: unknown) => listener(snapshot)
    ipcRenderer.on('qianchuan:statusChanged', handler)
    return () => ipcRenderer.removeListener('qianchuan:statusChanged', handler)
  },
})
